### ISSUE TITLE
Error after refresh server list page

### ISSUE THREAD

**Issue by WolverStones** [MrUniverse44/PixelMOTD2#2]
```[01:19:00 WARN]: Error dispatching event ProxyPingEvent(connection=[/127.0.0.1:62442] <-> InitialHandler, response=ServerPing(version=ServerPing.Protocol(name=Waterfall 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x, 1.17.x, protocol=756), players=ServerPing.Players(max=1, online=0, sample=null), description=Another Bungee server, modinfo=ServerPing.ModInfo(type=FML, modList=[]))) to listener dev.mruniverse.pixelmotd.bungeecord.motd.CustomMotdListener@7859e786
java.lang.NoClassDefFoundError: Could not initialize class dev.mruniverse.pixelmotd.global.iridiumcolorapi.IridiumColorAPI
        at dev.mruniverse.pixelmotd.bungeecord.motd.MotdInformation.getHexAllMotd(MotdInformation.java:81) ~[?:?]
        at dev.mruniverse.pixelmotd.bungeecord.motd.CustomMotdListener.onPingEvent(CustomMotdListener.java:127) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:48) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at net.md_5.bungee.connection.InitialHandler$3.done(InitialHandler.java:269) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at net.md_5.bungee.connection.InitialHandler$3.done(InitialHandler.java:245) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:278) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at net.md_5.bungee.protocol.packet.StatusRequest.handle(StatusRequest.java:30) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:253) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:514) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.17-447.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:62c18d4:447]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
[01:19:00 INFO]: [/127.0.0.1:62447] <-> InitialHandler has pinged```

**Comment by WolverStones** [comment]
Version: 9.0.0-PreRelease2
waterfall-1.17-448

**Comment by MrUniverse44** [comment]
Can you try redownloading ? the class exists but i don't have that issue.
https://cdn.discordapp.com/attachments/833395688834203669/877307640244478062/PixelMOTD-9.0.0-SNAPSHOT.jar

**Comment by WolverStones** [comment]
I downloaded the plugin from the link again, but unfortunately the error still persists.

**Comment by MrUniverse44** [comment]
that is strange, i will check this in waterfall.

**Comment by MrUniverse44** [comment]
Fixed on [Experimental-PreRelease3](https://github.com/MrUniverse44/PixelMOTD2/releases/tag/9.0.0-Experimental-PreRelease3)

**Comment by WolverStones** [comment]
Fixed, thanks!

> Fixed on [Experimental-PreRelease3](https://github.com/MrUniverse44/PixelMOTD2/releases/tag/9.0.0-Experimental-PreRelease3)
